FROM quay.io/keycloak/keycloak:26.7.0 AS builder

ENV KC_DB=postgres \
    KC_HEALTH_ENABLED=true \
    KC_METRICS_ENABLED=true

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:26.7.0

COPY --from=builder /opt/keycloak/ /opt/keycloak/
COPY --chown=keycloak:keycloak --chmod=0555 integrations/keycloak/entrypoint.sh /opt/keycloak/bin/decision-assurance-entrypoint.sh

USER 1000
ENTRYPOINT ["/opt/keycloak/bin/decision-assurance-entrypoint.sh"]
CMD ["start", "--optimized", "--import-realm"]
