from __future__ import annotations

from typing import Any, Protocol

from ..tenancy import TenantContext


class DecisionRepository(Protocol):
    def create_decision(self, tenant: TenantContext, document: dict[str, Any]) -> None: ...
    def get_decision(self, tenant: TenantContext, decision_id: str) -> dict[str, Any] | None: ...
    def save_result(self, tenant: TenantContext, document: dict[str, Any], report: dict[str, Any] | None, events: list[dict[str, Any]]) -> None: ...
    def get_report(self, tenant: TenantContext, decision_id: str) -> dict[str, Any] | None: ...
    def list_audit(self, tenant: TenantContext, decision_id: str, *, limit: int, offset: int) -> list[dict[str, Any]]: ...

